/*
 * Costco Fulfillment API
 *
 * An API for fullfilling orders placed on non-Costco channels by Costco 
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class Body2 : IEquatable<Body2>
    { 
        /// <summary>
        /// The Partner Generated Return Authorization Number. Sending a new unique value will result in a new Return Authorization being fulfilled. Sending a value that the service has seen before will result in the retrieval of an existing Return Authorization.
        /// </summary>
        /// <value>The Partner Generated Return Authorization Number. Sending a new unique value will result in a new Return Authorization being fulfilled. Sending a value that the service has seen before will result in the retrieval of an existing Return Authorization.</value>
        [Required]
        [DataMember(Name="partnerReturnAuthorizationNumber")]
        public string PartnerReturnAuthorizationNumber { get; set; }

        /// <summary>
        /// The customer service channel on which the return originated
        /// </summary>
        /// <value>The customer service channel on which the return originated</value>
        [Required]
        [DataMember(Name="channel")]
        public string Channel { get; set; }

        /// <summary>
        /// The Return LineItems
        /// </summary>
        /// <value>The Return LineItems</value>
        [Required]
        [DataMember(Name="lineItems")]
        public List<ReturnLineItem> LineItems { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Body2 {\n");
            sb.Append("  PartnerReturnAuthorizationNumber: ").Append(PartnerReturnAuthorizationNumber).Append("\n");
            sb.Append("  Channel: ").Append(Channel).Append("\n");
            sb.Append("  LineItems: ").Append(LineItems).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((Body2)obj);
        }

        /// <summary>
        /// Returns true if Body2 instances are equal
        /// </summary>
        /// <param name="other">Instance of Body2 to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Body2 other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    PartnerReturnAuthorizationNumber == other.PartnerReturnAuthorizationNumber ||
                    PartnerReturnAuthorizationNumber != null &&
                    PartnerReturnAuthorizationNumber.Equals(other.PartnerReturnAuthorizationNumber)
                ) && 
                (
                    Channel == other.Channel ||
                    Channel != null &&
                    Channel.Equals(other.Channel)
                ) && 
                (
                    LineItems == other.LineItems ||
                    LineItems != null &&
                    LineItems.SequenceEqual(other.LineItems)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (PartnerReturnAuthorizationNumber != null)
                    hashCode = hashCode * 59 + PartnerReturnAuthorizationNumber.GetHashCode();
                    if (Channel != null)
                    hashCode = hashCode * 59 + Channel.GetHashCode();
                    if (LineItems != null)
                    hashCode = hashCode * 59 + LineItems.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(Body2 left, Body2 right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(Body2 left, Body2 right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
