/*
 * Costco Fulfillment API
 *
 * An API for fullfilling orders placed on non-Costco channels by Costco 
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class Body7 : IEquatable<Body7>
    { 
        /// <summary>
        /// Gets or Sets Members
        /// </summary>
        [Required]
        [DataMember(Name="members")]
        public LoyaltyProgramsmembershipsMembers Members { get; set; }

        /// <summary>
        /// Gets or Sets MembershipOrder
        /// </summary>
        [Required]
        [DataMember(Name="membershipOrder")]
        public LoyaltyProgramsmembershipsMembershipOrder MembershipOrder { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Body7 {\n");
            sb.Append("  Members: ").Append(Members).Append("\n");
            sb.Append("  MembershipOrder: ").Append(MembershipOrder).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((Body7)obj);
        }

        /// <summary>
        /// Returns true if Body7 instances are equal
        /// </summary>
        /// <param name="other">Instance of Body7 to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Body7 other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Members == other.Members ||
                    Members != null &&
                    Members.Equals(other.Members)
                ) && 
                (
                    MembershipOrder == other.MembershipOrder ||
                    MembershipOrder != null &&
                    MembershipOrder.Equals(other.MembershipOrder)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Members != null)
                    hashCode = hashCode * 59 + Members.GetHashCode();
                    if (MembershipOrder != null)
                    hashCode = hashCode * 59 + MembershipOrder.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(Body7 left, Body7 right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(Body7 left, Body7 right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
