/*
 * Costco Fulfillment API
 *
 * An API for fullfilling orders placed on non-Costco channels by Costco 
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
        /// <summary>
        /// Non-Production Environment Identifier
        /// </summary>
        /// <value>Non-Production Environment Identifier</value>
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum CostcoEnv
        {
            
            /// <summary>
            /// Enum DIT5Enum for DIT5
            /// </summary>
            [EnumMember(Value = "DIT5")]
            DIT5Enum = 1,
            
            /// <summary>
            /// Enum QA2Enum for QA2
            /// </summary>
            [EnumMember(Value = "QA2")]
            QA2Enum = 2
        }
}
