/*
 * Costco Fulfillment API
 *
 * An API for fullfilling orders placed on non-Costco channels by Costco 
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class InlineResponse2004 : IEquatable<InlineResponse2004>
    { 
        /// <summary>
        /// Gets or Sets Result
        /// </summary>
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum ResultEnum
        {
            
            /// <summary>
            /// Enum OkEnum for ok
            /// </summary>
            [EnumMember(Value = "ok")]
            OkEnum = 1,
            
            /// <summary>
            /// Enum OkWithExceptionsEnum for okWithExceptions
            /// </summary>
            [EnumMember(Value = "okWithExceptions")]
            OkWithExceptionsEnum = 2
        }

        /// <summary>
        /// Gets or Sets Result
        /// </summary>
        [Required]
        [DataMember(Name="result")]
        public ResultEnum? Result { get; set; }

        /// <summary>
        /// Gets or Sets PartnerOrder
        /// </summary>
        [Required]
        [DataMember(Name="partnerOrder")]
        public InlineResponse2004PartnerOrder PartnerOrder { get; set; }

        /// <summary>
        /// The Order Number Representing an Order for Undelivered Items
        /// </summary>
        /// <value>The Order Number Representing an Order for Undelivered Items</value>
        [DataMember(Name="undeliveredItemsPartnerOrderNumber")]
        public string UndeliveredItemsPartnerOrderNumber { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class InlineResponse2004 {\n");
            sb.Append("  Result: ").Append(Result).Append("\n");
            sb.Append("  PartnerOrder: ").Append(PartnerOrder).Append("\n");
            sb.Append("  UndeliveredItemsPartnerOrderNumber: ").Append(UndeliveredItemsPartnerOrderNumber).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((InlineResponse2004)obj);
        }

        /// <summary>
        /// Returns true if InlineResponse2004 instances are equal
        /// </summary>
        /// <param name="other">Instance of InlineResponse2004 to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(InlineResponse2004 other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Result == other.Result ||
                    Result != null &&
                    Result.Equals(other.Result)
                ) && 
                (
                    PartnerOrder == other.PartnerOrder ||
                    PartnerOrder != null &&
                    PartnerOrder.Equals(other.PartnerOrder)
                ) && 
                (
                    UndeliveredItemsPartnerOrderNumber == other.UndeliveredItemsPartnerOrderNumber ||
                    UndeliveredItemsPartnerOrderNumber != null &&
                    UndeliveredItemsPartnerOrderNumber.Equals(other.UndeliveredItemsPartnerOrderNumber)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Result != null)
                    hashCode = hashCode * 59 + Result.GetHashCode();
                    if (PartnerOrder != null)
                    hashCode = hashCode * 59 + PartnerOrder.GetHashCode();
                    if (UndeliveredItemsPartnerOrderNumber != null)
                    hashCode = hashCode * 59 + UndeliveredItemsPartnerOrderNumber.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(InlineResponse2004 left, InlineResponse2004 right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(InlineResponse2004 left, InlineResponse2004 right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
