/*
 * Costco Fulfillment API
 *
 * An API for fullfilling orders placed on non-Costco channels by Costco 
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
    /// <summary>
    /// A Representation of an Order Header
    /// </summary>
    [DataContract]
    public partial class InlineResponse2005PartnerOrderOrderSummary : IEquatable<InlineResponse2005PartnerOrderOrderSummary>
    { 
        /// <summary>
        /// The order number generated for non-Costco systems
        /// </summary>
        /// <value>The order number generated for non-Costco systems</value>
        [Required]
        [DataMember(Name="partnerOrderNumber")]
        public string PartnerOrderNumber { get; set; }

        /// <summary>
        /// the moment at which the order was generated in ISO 8601 format.
        /// </summary>
        /// <value>the moment at which the order was generated in ISO 8601 format.</value>
        [Required]
        [DataMember(Name="placeOrderTime")]
        public DateTime? PlaceOrderTime { get; set; }

        /// <summary>
        /// the currency code for which all monetary values will be assumed
        /// </summary>
        /// <value>the currency code for which all monetary values will be assumed</value>
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum CurrencyEnum
        {
            
            /// <summary>
            /// Enum USDEnum for USD
            /// </summary>
            [EnumMember(Value = "USD")]
            USDEnum = 1
        }

        /// <summary>
        /// the currency code for which all monetary values will be assumed
        /// </summary>
        /// <value>the currency code for which all monetary values will be assumed</value>
        [DataMember(Name="currency")]
        public CurrencyEnum? Currency { get; set; }

        /// <summary>
        /// The total cost of the order minus shipping, tips and taxes, represented as a number
        /// </summary>
        /// <value>The total cost of the order minus shipping, tips and taxes, represented as a number</value>
        [Required]
        [DataMember(Name="subtotal")]
        public decimal? Subtotal { get; set; }

        /// <summary>
        /// The total cost of taxes on the order, represented as a number
        /// </summary>
        /// <value>The total cost of taxes on the order, represented as a number</value>
        [Required]
        [DataMember(Name="taxTotal")]
        public decimal? TaxTotal { get; set; }

        /// <summary>
        /// The total cost of shipping on the order, represented as a number
        /// </summary>
        /// <value>The total cost of shipping on the order, represented as a number</value>
        [DataMember(Name="shippingTotal")]
        public decimal? ShippingTotal { get; set; }

        /// <summary>
        /// the total cost of a tip on the order, represented as a number
        /// </summary>
        /// <value>the total cost of a tip on the order, represented as a number</value>
        [DataMember(Name="tipTotal")]
        public decimal? TipTotal { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class InlineResponse2005PartnerOrderOrderSummary {\n");
            sb.Append("  PartnerOrderNumber: ").Append(PartnerOrderNumber).Append("\n");
            sb.Append("  PlaceOrderTime: ").Append(PlaceOrderTime).Append("\n");
            sb.Append("  Currency: ").Append(Currency).Append("\n");
            sb.Append("  Subtotal: ").Append(Subtotal).Append("\n");
            sb.Append("  TaxTotal: ").Append(TaxTotal).Append("\n");
            sb.Append("  ShippingTotal: ").Append(ShippingTotal).Append("\n");
            sb.Append("  TipTotal: ").Append(TipTotal).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((InlineResponse2005PartnerOrderOrderSummary)obj);
        }

        /// <summary>
        /// Returns true if InlineResponse2005PartnerOrderOrderSummary instances are equal
        /// </summary>
        /// <param name="other">Instance of InlineResponse2005PartnerOrderOrderSummary to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(InlineResponse2005PartnerOrderOrderSummary other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    PartnerOrderNumber == other.PartnerOrderNumber ||
                    PartnerOrderNumber != null &&
                    PartnerOrderNumber.Equals(other.PartnerOrderNumber)
                ) && 
                (
                    PlaceOrderTime == other.PlaceOrderTime ||
                    PlaceOrderTime != null &&
                    PlaceOrderTime.Equals(other.PlaceOrderTime)
                ) && 
                (
                    Currency == other.Currency ||
                    Currency != null &&
                    Currency.Equals(other.Currency)
                ) && 
                (
                    Subtotal == other.Subtotal ||
                    Subtotal != null &&
                    Subtotal.Equals(other.Subtotal)
                ) && 
                (
                    TaxTotal == other.TaxTotal ||
                    TaxTotal != null &&
                    TaxTotal.Equals(other.TaxTotal)
                ) && 
                (
                    ShippingTotal == other.ShippingTotal ||
                    ShippingTotal != null &&
                    ShippingTotal.Equals(other.ShippingTotal)
                ) && 
                (
                    TipTotal == other.TipTotal ||
                    TipTotal != null &&
                    TipTotal.Equals(other.TipTotal)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (PartnerOrderNumber != null)
                    hashCode = hashCode * 59 + PartnerOrderNumber.GetHashCode();
                    if (PlaceOrderTime != null)
                    hashCode = hashCode * 59 + PlaceOrderTime.GetHashCode();
                    if (Currency != null)
                    hashCode = hashCode * 59 + Currency.GetHashCode();
                    if (Subtotal != null)
                    hashCode = hashCode * 59 + Subtotal.GetHashCode();
                    if (TaxTotal != null)
                    hashCode = hashCode * 59 + TaxTotal.GetHashCode();
                    if (ShippingTotal != null)
                    hashCode = hashCode * 59 + ShippingTotal.GetHashCode();
                    if (TipTotal != null)
                    hashCode = hashCode * 59 + TipTotal.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(InlineResponse2005PartnerOrderOrderSummary left, InlineResponse2005PartnerOrderOrderSummary right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(InlineResponse2005PartnerOrderOrderSummary left, InlineResponse2005PartnerOrderOrderSummary right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
