/*
 * Shipments API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class InlineResponse200LineItems : IEquatable<InlineResponse200LineItems>
    { 
        /// <summary>
        /// Gets or Sets LineProcessingStatus
        /// </summary>
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum LineProcessingStatusEnum
        {
            
            /// <summary>
            /// Enum InvalidItemEnum for invalidItem
            /// </summary>
            [EnumMember(Value = "invalidItem")]
            InvalidItemEnum = 1,
            
            /// <summary>
            /// Enum InvalidLineQuantityEnum for invalidLineQuantity
            /// </summary>
            [EnumMember(Value = "invalidLineQuantity")]
            InvalidLineQuantityEnum = 2,
            
            /// <summary>
            /// Enum InvalidLineStatusEnum for invalidLineStatus
            /// </summary>
            [EnumMember(Value = "invalidLineStatus")]
            InvalidLineStatusEnum = 3
        }

        /// <summary>
        /// Gets or Sets LineProcessingStatus
        /// </summary>
        [Required]
        [DataMember(Name="lineProcessingStatus")]
        public LineProcessingStatusEnum? LineProcessingStatus { get; set; }

        /// <summary>
        /// The Costco item number to be fulfilled
        /// </summary>
        /// <value>The Costco item number to be fulfilled</value>
        [Required]
        [DataMember(Name="itemNumber")]
        public decimal? ItemNumber { get; set; }

        /// <summary>
        /// The quantity of units to be fulfilled
        /// </summary>
        /// <value>The quantity of units to be fulfilled</value>
        [Required]
        [DataMember(Name="quantity")]
        public decimal? Quantity { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class InlineResponse200LineItems {\n");
            sb.Append("  LineProcessingStatus: ").Append(LineProcessingStatus).Append("\n");
            sb.Append("  ItemNumber: ").Append(ItemNumber).Append("\n");
            sb.Append("  Quantity: ").Append(Quantity).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((InlineResponse200LineItems)obj);
        }

        /// <summary>
        /// Returns true if InlineResponse200LineItems instances are equal
        /// </summary>
        /// <param name="other">Instance of InlineResponse200LineItems to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(InlineResponse200LineItems other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    LineProcessingStatus == other.LineProcessingStatus ||
                    LineProcessingStatus != null &&
                    LineProcessingStatus.Equals(other.LineProcessingStatus)
                ) && 
                (
                    ItemNumber == other.ItemNumber ||
                    ItemNumber != null &&
                    ItemNumber.Equals(other.ItemNumber)
                ) && 
                (
                    Quantity == other.Quantity ||
                    Quantity != null &&
                    Quantity.Equals(other.Quantity)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (LineProcessingStatus != null)
                    hashCode = hashCode * 59 + LineProcessingStatus.GetHashCode();
                    if (ItemNumber != null)
                    hashCode = hashCode * 59 + ItemNumber.GetHashCode();
                    if (Quantity != null)
                    hashCode = hashCode * 59 + Quantity.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(InlineResponse200LineItems left, InlineResponse200LineItems right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(InlineResponse200LineItems left, InlineResponse200LineItems right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
