/*
 * Costco Fulfillment API
 *
 * An API for fullfilling orders placed on non-Costco channels by Costco 
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class LineItemLinkedFees : IEquatable<LineItemLinkedFees>
    { 
        /// <summary>
        /// Costco Provided Linked Fee Item Number
        /// </summary>
        /// <value>Costco Provided Linked Fee Item Number</value>
        [Required]
        [DataMember(Name="feeSku")]
        public string FeeSku { get; set; }

        /// <summary>
        /// Unit Price of Fee Item, represented as a number
        /// </summary>
        /// <value>Unit Price of Fee Item, represented as a number</value>
        [Required]
        [DataMember(Name="feeUnitPrice")]
        public decimal? FeeUnitPrice { get; set; }

        /// <summary>
        /// The cost of tax for a unit, represented as a number
        /// </summary>
        /// <value>The cost of tax for a unit, represented as a number</value>
        [Required]
        [DataMember(Name="feeUnitTaxPrice")]
        public string FeeUnitTaxPrice { get; set; }

        /// <summary>
        /// Quantity of Fee Items
        /// </summary>
        /// <value>Quantity of Fee Items</value>
        [Required]
        [DataMember(Name="quantity")]
        public int? Quantity { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class LineItemLinkedFees {\n");
            sb.Append("  FeeSku: ").Append(FeeSku).Append("\n");
            sb.Append("  FeeUnitPrice: ").Append(FeeUnitPrice).Append("\n");
            sb.Append("  FeeUnitTaxPrice: ").Append(FeeUnitTaxPrice).Append("\n");
            sb.Append("  Quantity: ").Append(Quantity).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((LineItemLinkedFees)obj);
        }

        /// <summary>
        /// Returns true if LineItemLinkedFees instances are equal
        /// </summary>
        /// <param name="other">Instance of LineItemLinkedFees to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(LineItemLinkedFees other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    FeeSku == other.FeeSku ||
                    FeeSku != null &&
                    FeeSku.Equals(other.FeeSku)
                ) && 
                (
                    FeeUnitPrice == other.FeeUnitPrice ||
                    FeeUnitPrice != null &&
                    FeeUnitPrice.Equals(other.FeeUnitPrice)
                ) && 
                (
                    FeeUnitTaxPrice == other.FeeUnitTaxPrice ||
                    FeeUnitTaxPrice != null &&
                    FeeUnitTaxPrice.Equals(other.FeeUnitTaxPrice)
                ) && 
                (
                    Quantity == other.Quantity ||
                    Quantity != null &&
                    Quantity.Equals(other.Quantity)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (FeeSku != null)
                    hashCode = hashCode * 59 + FeeSku.GetHashCode();
                    if (FeeUnitPrice != null)
                    hashCode = hashCode * 59 + FeeUnitPrice.GetHashCode();
                    if (FeeUnitTaxPrice != null)
                    hashCode = hashCode * 59 + FeeUnitTaxPrice.GetHashCode();
                    if (Quantity != null)
                    hashCode = hashCode * 59 + Quantity.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(LineItemLinkedFees left, LineItemLinkedFees right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(LineItemLinkedFees left, LineItemLinkedFees right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
