/*
 * Costco Fullfillment API
 *
 * An API for fullfilling orders placed on non-Costco channels by Costco 
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
    /// <summary>
    /// A Representation of an Order Line
    /// </summary>
    [DataContract]
    public partial class LineItem :  IEquatable<LineItem>
    { 
        /// <summary>
        /// The unique id of the line item that is shipped
        /// </summary>
        /// <value>The unique id of the line item that is shipped</value>
        [Required]
        [DataMember(Name="referenceNumber")]
        public string ReferenceNumber { get; set; }

        /// <summary>
        /// The Costco item number to be fulfilled
        /// </summary>
        /// <value>The Costco item number to be fulfilled</value>
        [Required]
        [DataMember(Name="itemNumber")]
        public string ItemNumber { get; set; }

        /// <summary>
        /// The quantity of units to be fulfilled
        /// </summary>
        /// <value>The quantity of units to be fulfilled</value>
        [Required]
        [DataMember(Name="quantity")]
        public decimal? Quantity { get; set; }

        /// <summary>
        /// The sales price of unit, represented as a number
        /// </summary>
        /// <value>The sales price of unit, represented as a number</value>
        [Required]
        [DataMember(Name="unitSellPrice")]
        public decimal? UnitSellPrice { get; set; }

        /// <summary>
        /// The cost of tax for a unit, represented as a number
        /// </summary>
        /// <value>The cost of tax for a unit, represented as a number</value>
        [Required]
        [DataMember(Name="unitItemTaxPrice")]
        public decimal? UnitItemTaxPrice { get; set; }

        /// <summary>
        /// The cost of shipping for a unit, represented as a number
        /// </summary>
        /// <value>The cost of shipping for a unit, represented as a number</value>
        [Required]
        [DataMember(Name="unitShippingPrice")]
        public decimal? UnitShippingPrice { get; set; }

        /// <summary>
        /// The cost of tax on shipping of a unit, represented as a number
        /// </summary>
        /// <value>The cost of tax on shipping of a unit, represented as a number</value>
        [Required]
        [DataMember(Name="unitShippingTaxPrice")]
        public decimal? UnitShippingTaxPrice { get; set; }

        /// <summary>
        /// A collection of Costco coupons applied to a line
        /// </summary>
        /// <value>A collection of Costco coupons applied to a line</value>
        [DataMember(Name="coupons")]
        public List<Coupon> Coupons { get; set; }

        /// <summary>
        /// A collection of linked fees associated with a line
        /// </summary>
        /// <value>A collection of linked fees associated with a line</value>
        [DataMember(Name="linkedFees")]
        public List<LinkedFee> LinkedFees { get; set; }

        /// <summary>
        /// Gets or Sets DeliveryDetail
        /// </summary>
        [Required]
        [DataMember(Name="deliveryDetail")]
        public DeliveryDetail DeliveryDetail { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class LineItem {\n");
            sb.Append("  ReferenceNumber: ").Append(ReferenceNumber).Append("\n");
            sb.Append("  ItemNumber: ").Append(ItemNumber).Append("\n");
            sb.Append("  Quantity: ").Append(Quantity).Append("\n");
            sb.Append("  UnitSellPrice: ").Append(UnitSellPrice).Append("\n");
            sb.Append("  UnitItemTaxPrice: ").Append(UnitItemTaxPrice).Append("\n");
            sb.Append("  UnitShippingPrice: ").Append(UnitShippingPrice).Append("\n");
            sb.Append("  UnitShippingTaxPrice: ").Append(UnitShippingTaxPrice).Append("\n");
            sb.Append("  Coupons: ").Append(Coupons).Append("\n");
            sb.Append("  LinkedFees: ").Append(LinkedFees).Append("\n");
            sb.Append("  DeliveryDetail: ").Append(DeliveryDetail).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((LineItem)obj);
        }

        /// <summary>
        /// Returns true if LineItem instances are equal
        /// </summary>
        /// <param name="other">Instance of LineItem to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(LineItem other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    ReferenceNumber == other.ReferenceNumber ||
                    ReferenceNumber != null &&
                    ReferenceNumber.Equals(other.ReferenceNumber)
                ) && 
                (
                    ItemNumber == other.ItemNumber ||
                    ItemNumber != null &&
                    ItemNumber.Equals(other.ItemNumber)
                ) && 
                (
                    Quantity == other.Quantity ||
                    Quantity != null &&
                    Quantity.Equals(other.Quantity)
                ) && 
                (
                    UnitSellPrice == other.UnitSellPrice ||
                    UnitSellPrice != null &&
                    UnitSellPrice.Equals(other.UnitSellPrice)
                ) && 
                (
                    UnitItemTaxPrice == other.UnitItemTaxPrice ||
                    UnitItemTaxPrice != null &&
                    UnitItemTaxPrice.Equals(other.UnitItemTaxPrice)
                ) && 
                (
                    UnitShippingPrice == other.UnitShippingPrice ||
                    UnitShippingPrice != null &&
                    UnitShippingPrice.Equals(other.UnitShippingPrice)
                ) && 
                (
                    UnitShippingTaxPrice == other.UnitShippingTaxPrice ||
                    UnitShippingTaxPrice != null &&
                    UnitShippingTaxPrice.Equals(other.UnitShippingTaxPrice)
                ) && 
                (
                    Coupons == other.Coupons ||
                    Coupons != null &&
                    Coupons.SequenceEqual(other.Coupons)
                ) && 
                (
                    LinkedFees == other.LinkedFees ||
                    LinkedFees != null &&
                    LinkedFees.SequenceEqual(other.LinkedFees)
                ) && 
                (
                    DeliveryDetail == other.DeliveryDetail ||
                    DeliveryDetail != null &&
                    DeliveryDetail.Equals(other.DeliveryDetail)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (ReferenceNumber != null)
                    hashCode = hashCode * 59 + ReferenceNumber.GetHashCode();
                    if (ItemNumber != null)
                    hashCode = hashCode * 59 + ItemNumber.GetHashCode();
                    if (Quantity != null)
                    hashCode = hashCode * 59 + Quantity.GetHashCode();
                    if (UnitSellPrice != null)
                    hashCode = hashCode * 59 + UnitSellPrice.GetHashCode();
                    if (UnitItemTaxPrice != null)
                    hashCode = hashCode * 59 + UnitItemTaxPrice.GetHashCode();
                    if (UnitShippingPrice != null)
                    hashCode = hashCode * 59 + UnitShippingPrice.GetHashCode();
                    if (UnitShippingTaxPrice != null)
                    hashCode = hashCode * 59 + UnitShippingTaxPrice.GetHashCode();
                    if (Coupons != null)
                    hashCode = hashCode * 59 + Coupons.GetHashCode();
                    if (LinkedFees != null)
                    hashCode = hashCode * 59 + LinkedFees.GetHashCode();
                    if (DeliveryDetail != null)
                    hashCode = hashCode * 59 + DeliveryDetail.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(LineItem left, LineItem right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(LineItem left, LineItem right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
