{
  "swagger" : "2.0",
  "info" : {
    "description" : "An API for fullfilling orders placed on non-Costco channels by Costco\n",
    "version" : "1.0.0",
    "title" : "Costco Fulfillment API",
    "termsOfService" : "",
    "contact" : { }
  },
  "host" : "api.costco.com",
  "basePath" : "/ebusiness",
  "schemes" : [ "https" ],
  "security" : [ {
    "OAuth2" : [ ]
  } ],
  "paths" : {
    "/costing/shippingFees" : {
      "post" : {
        "tags" : [ "costing" ],
        "summary" : "Retrieve Shipping Fees",
        "security" : [ {
          "OAuth2" : [ "order operator" ]
        } ]
      }
    },
    "/costing/linkedFees" : {
      "post" : {
        "tags" : [ "costing " ],
        "summary" : "Retrieve Linked Fees",
        "description" : "[Final]",
        "security" : [ {
          "OAuth2" : [ "order operator" ]
        } ]
      }
    },
    "/{salesChannelId}/order" : {
      "post" : {
        "tags" : [ "order" ],
        "summary" : "Create an Order Async",
        "description" : "[Final] Creates an Order at Costco to be fulfilled",
        "security" : [ {
          "OAuth2" : [ "order operator" ]
        } ]
      }
    },
    "/{salesChannelId}/order/{partnerOrderNumber}" : {
      "get" : {
        "tags" : [ "order" ],
        "summary" : "Retrieve Order Details",
        "description" : "[Final]  Returns Order Line Details",
        "security" : [ {
          "OAuth2" : [ "order fulfiller" ]
        } ]
      },
      "delete" : {
        "tags" : [ "order" ],
        "summary" : "Cancel an Order",
        "description" : "[In Design] Attempts cancellation of an order being fullfilled at Costco",
        "security" : [ {
          "OAuth2" : [ "order fulfiller" ]
        } ]
      }
    },
    "/{salesChannelId}/order/{partnerOrderNumber}/return" : {
      "post" : {
        "tags" : [ "order", "return" ],
        "summary" : "Request Return Authorization",
        "description" : "[Final]",
        "security" : [ {
          "OAuth2" : [ "order operator" ]
        } ]
      }
    },
    "/{salesChannelId}/order/{partnerOrderNumber}/refund" : {
      "post" : {
        "tags" : [ "order", "return" ],
        "summary" : "Notification of Customer Refund",
        "description" : "[In Design] ",
        "security" : [ {
          "OAuth2" : [ "order operator", "order fulfiller" ]
        } ]
      }
    },
    "/{salesChannelId}/order/{partnerOrderNumber}/fulfill" : {
      "post" : {
        "tags" : [ "order" ],
        "summary" : "Fulfill Order",
        "description" : "[Final]  ",
        "security" : [ {
          "OAuth2" : [ "order fulfiller" ]
        } ]
      },
      "put" : {
        "tags" : [ "order" ],
        "summary" : "Notification of Status Change",
        "description" : "[Final]",
        "security" : [ {
          "OAuth2" : [ "order fulfiller" ]
        } ]
      }
    },
    "/{salesChannelId}/order/{partnerOrderNumber}/adjustTip" : {
      "put" : {
        "tags" : [ "order" ],
        "summary" : "Request Tip Adjustment",
        "description" : "[Final]  ",
        "security" : [ {
          "OAuth2" : [ "order fulfiller" ]
        } ]
      }
    },
    "/{salesChannelId}/return/{partnerReturnAuthorizationNumber}" : {
      "delete" : {
        "tags" : [ "return" ],
        "summary" : "Cancel Return Authorization",
        "security" : [ {
          "OAuth2" : [ "order operator" ]
        } ]
      }
    },
    "/loyaltyPrograms/memberships/" : {
      "post" : {
        "tags" : [ "customers" ],
        "summary" : "Purchase Membership"
      }
    }
  },
  "securityDefinitions" : {
    "OAuth2" : {
      "type" : "oauth2",
      "tokenUrl" : "https://costcofulfillment.azurewebsites.net/token",
      "flow" : "application",
      "scopes" : {
        "order operator" : "Can perform operations to capture orders and have them fulfilled by Costco",
        "order fulfiller" : "Can perform operations to fulfill orders captured by Costco"
      }
    }
  }
}
